# eks_auth.yml
.gitlab_eks_setup:
  image: $ECR_ROOT/devops/golden_runner:1.1.1
  variables:
    AWS_REGION: "us-west-1"
    AWS_ROLE_ARN: "arn:aws-us-gov:iam::$AWS_ACCOUNT_ID:role/gitlab-runner-eks-role"
    EKS_CLUSTER_NAME: "isaac-eks-cluster"
  before_script:
    - set -euo pipefail
    - git config --global user.name "${GITLAB_RO_USERNAME}"
    - git config --global user.email "ci-bot@gmail.com"
    - git config --global url."https://${GITLAB_RO_USERNAME}:${GITLAB_RO_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
    - echo "Logging into Azure AD..."
    - az login --service-principal -u "$EKS_CLIENT_ID" -p "$EKS_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID" --allow-no-subscriptions
    - export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/azure_token"
    - AZURE_TOKEN=$(az account get-access-token --resource "api://$EKS_CLIENT_ID" --query accessToken -o tsv)
    - printf "%s" "$AZURE_TOKEN" > "$AWS_WEB_IDENTITY_TOKEN_FILE"
    - unset AZURE_TOKEN
    - export AWS_ROLE_SESSION_NAME="gitlab-runner-session"
    - echo "Assuming AWS role $AWS_ROLE_ARN ..."
    - CREDS=$(aws sts assume-role-with-web-identity --role-arn "$AWS_ROLE_ARN" --role-session-name "$AWS_ROLE_SESSION_NAME" --web-identity-token "file://$AWS_WEB_IDENTITY_TOKEN_FILE" --duration-seconds 3600 --no-cli-pager)
    - export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' <<< "$CREDS")
    - export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' <<< "$CREDS")
    - export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' <<< "$CREDS")
    - rm -f "$AWS_WEB_IDENTITY_TOKEN_FILE"
    - set -x
    - aws sts get-caller-identity --no-cli-pager
    - echo "AWS credentials set up successfully."
    - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
    - kubectl get nodes
